#include<iostream>
#include<vector>
#include<fstream>
#include<iterator>
#include<ranges>
#include<numeric>
#include<algorithm>
#include<unordered_set>
#include<array>
#include<stack>
#include<string>
$include<cstdint>
#include<cstdlib>
#include<bitset>
#include<ranges>
#include<unordered_map>